<form id="form-agent" action="index.php?page=agent&action=edit&id=<?= $leClient->getId() ?>" method="post"
    enctype="multipart/form-data">

    <fieldset>

        <legend><span class="number">1</span> Informations personnelles</legend>

        <label for="name">Civilité:</label>
        <select name="cbCivilite" id="chCbCivilite">
            <?php
        foreach ($lesCivilites as $civilite){
          if ($civilite->getId() == $leClient->getCivilite()->getId()){
            print('<option value="'.$civilite->getId().'">'.$civilite->getLibelleLong().'</option>');
          }else{
            print('<option value="'.$civilite->getId().'">'.$civilite->getLibelleLong().'</option>');
          }
        }
      ?>
        </select>

        <label for="champNom">Nom:</label>
        <input type="text" id="champNom" value="<?php echo $leClient->getNom(); ?>" name="chNom">

        <label for="champPrenom">Prénom:</label>
        <input type="text" id="champPrenom" value="<?php echo $leClient->getPrenom(); ?>" name="chPrenom">

        <label for="champTelephone">Téléphone:</label>
        <input type="text" id="champTelephone" value="<?php echo $leClient->getTelephone(); ?>" name="chTelephone">

        <label for="champMail">Email:</label>
        <input type="email" id="champMail" value="<?php echo $leClient->getMail(); ?>" name="chMail">

    </fieldset>
    <fieldset>

        <legend><span class="number">2</span> Adresse</legend>

        <label for="champTel">Numéro de rue:</label>
        <input type="text" id="champNumRue" value="<?php echo $leClient->getNumRue(); ?>" name="chNumRue">

        <label for="champRue">Nom de rue:</label>
        <input type="text" id="champNomRue" value="<?php echo $leClient->getNomRue(); ?>" name="chNomRue">

        <label for="champVille">Ville:</label>
        <input type="text" id="champVille" value="<?php echo $leClient->getVille(); ?>" name="chVille">

    </fieldset>
    <fieldset>
        <legend><span class="number">3</span> Informations complémentaires</legend>
        <label for="champCommentaire">Commentaire:</label>
        <textarea id="champCommentaire" name="chCommentaire"><?php echo $leClient->getCommentaire(); ?></textarea>
    </fieldset>

    <button type="submit">Confirmer modifications</button>

</form>