<a href="index.php?page=client&action=profil">
    <div class="card">
        <div class="card-content">
            <div class="icon_client"><i class="fa-solid fa-user"></i></div>
            <div class="label">Mes informations</div>
        </div>
    </div>
</a>

<a href="index.php?page=client&action=document">
    <div class="card">
        <div class="card-content">
            <div class="icon_client"><i class="fa-solid fa-folder-open"></i></div>
            <div class="label">Mes documents</div>
        </div>
    </div>
</a>

<a href="index.php?page=client&action=incident">
    <div class="card">
        <div class="card-content">
            <div class="icon_client"><i class="fa-solid fa-circle-exclamation"></i></div>
            <div class="label">Mes incidents</div>
        </div>
    </div>
</a>

<div class="card">
    <div class="card-content">
        <div class="icon_client"><i class="fa-regular fa-building"></i></div>
        <div class="label">Mon agence</div>
    </div>
</div>

<div class="card transparent">
    <div class="card-content">
        <img class="logo_black" src="public/medias/imgs/logo_black.png">
    </div>
</div>

<div class="card">
    <div class="card-content">
        <div class="icon_client"><i class="fa-solid fa-calendar-days"></i></div>
        <div class="label">Mon agenda</div>
    </div>
</div>

<div class="card">
    <div class="card-content">
        <div class="icon_client"><i class="fa-solid fa-file-circle-question"></i></div>
        <div class="label">FAQ</div>
    </div>
</div>

<div class="card">
    <div class="card-content">
        <div class="icon_client"><i class="fa-solid fa-square-phone"></i></div>
        <div class="label">Nous contacter</div>
    </div>
</div>

<div class="card">
    <div class="card-content">
        <div class="icon_client"><i class="fa-solid fa-file-signature"></i></div>
        <div class="label">Mon contrat</div>
    </div>
</div>