<div class="menu-client">

    <ul>
        <li><a href="index.php?page=client&action=main"><img class="logo-menu"
                    src="public/medias/imgs/logo_white.png"></a></li>
        <li><a href="index.php?page=client&action=profil">Mes informations</a></li>
        <li><a href="index.php?page=client&action=document">Mes documents</a></li>
        <li><a href="index.php?page=client&action=incident">Mes incidents</a></li>
        <li><a href="#">Nous contacter</a></li>
        <li><a href="index.php?page=users&action=login">Déconnexion</a></li>
    </ul>
</div>