<section class="sidebar">
    <div class="brand">
        <a href="index.php"><img class="logo" src="public/medias/imgs/logo.png" alt="Logo Share Immo"></a>
    </div>

    <nav class="main-nav">

        <ul class="main-menu menu">
            <li class="menu-item">
                <a href="index.php"> Liste des clients </a>
            </li>

            <li class="menu-item">
                <a href="index.php?page=agent&action=add"> Ajouter un client </a>
            </li>

            <li class="menu-item">
                <a href="index.php?page=agent&action=incident"> Gérer les incidents </a>
            </li>

            <li class="menu-item">
                <a href="#"> Gérer les documents </a>
            </li>

            <li class="menu-item">
                <a href="#"> Mes rendez-vous </a>
            </li>

            <li class="menu-item">
                <a href="#"> Liste des prestataires </a>
            </li>

        </ul>

        <ul class="main-menu sub-menu menu">
            <li class="menu-item">
                <a href="#"> Contacter le support </a>
            </li>

            <li class="menu-item">
                <a href="#"> Aide et dépannage </a>
            </li>

        </ul>

    </nav>


</section>