<section class="user-detail">

    <div class="profile-info">

        <div class="desc">
            <h3 class="name"> <?= $leClient->getPrenom() . ' ' . $leClient->getNom() ?>
                <span class="delete-element"> <a
                        href="index.php?page=agent&action=delete&id=<?= $leClient->getId() ?>"><i
                            class="fa-solid fa-trash-can"></i></a>
                    <span class="edit-element"> <a
                            href="index.php?page=agent&action=edit&id=<?= $leClient->getId() ?>"><i
                                class="fa-solid fa-pen-to-square"></i></a></span>
                    <span class="upload-element"> <a
                            href="index.php?page=agent&action=upload&id=<?= $leClient->getId() ?>"><i
                                class="fa-solid fa-folder-open"></i></a></span>
            </h3>
            <h5> <?= $leClient->getVille() ?> </h5>
            <div class="reviews">
                <span class="count"> <?php echo $nombreIncident ?> </span>
                <span> Incidents </span>
            </div>
        </div>
    </div>


    <div class="basic-details profile-item">
        <h4> Informations </h4>
        <ul class="info">
            <li> <i class="fa fa-comment-o"> </i> <span> <?= $leClient->getMail() ?> </span> </li>
            <li> <i class="fa fa-mobile"> </i> <span> <?= $leClient->getTelephone() ?> </span> </li>
            <li> <i class="fa fa-map-marker"> </i> <span> <?= $leClient->getVille() ?> </span> </li>
        </ul>

        <ul class="info">
            <li> <i class="fa fa-map-marker"> </i> <span> <?= $leClient->getNumRue() . ' ' . $leClient->getNomRue() ?>
                </span> </li>
        </ul>
    </div>


    <div class="bio-details profile-item">
        <h4> Commentaires </h4>
        <p class="desc"> <?= $leClient->getCommentaire() ?> </p>
    </div>

</section>
</div>
</section>