<div id="side-menu">
    <div class="wrapper-menu">
        <div class="side-icons">
            <ul>
                <li><a href="index.php?page=client&action=main"><i class="fa-solid fa-house"></i></a></li>
                <li><a href="index.php?page=client&action=document"><i class="fa-solid fa-folder-open"></i></a></li>
                <li><a href="index.php?page=client&action=profil"><i class="fa-solid fa-gear"></i></a></li>
                <li><a href="index.php?page=users&action=logout"><i
                            class="fa-solid fa-arrow-right-from-bracket logout"></i></a></li>
            </ul>
        </div>
    </div>
</div>