<?php
	ini_set('display_errors', 'on');
	require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">

<head>
    <?php require "includes/partials/page_head.phtml"; ?>
</head>

<body>
    <div class="layout">
        <?php require_once "includes/partials/navbar.phtml"; ?>

        <section class="content">
            <?php require_once "includes/partials/header.phtml"; ?>

            <div class="container container red">
                <h1>Le compte a bien été créé</h1>
                <h3>Identifiant : <?php echo $leClientPass['username'] ?></h3>
                <h3>Mot de passe : <?php echo $leClientPass['password'] ?></h3>
                <p>Veuillez communiquer impérativement ces informations au client avant de quitter cette page</p>.
            </div>

        </section>

    </div>

</body>

</html>